import nodemailer from 'nodemailer';
import logger from './logger.js';

export async function sendEmailWithAttachment(filePath, recipients, subject, fromName, requestId) {
  try {
    const transporter = nodemailer.createTransport({
      host: process.env.SMTP_HOST,
      port: parseInt(process.env.SMTP_PORT),
      secure: false,
      auth: {
        user: process.env.SMTP_USER,
        pass: process.env.SMTP_PASS,
      },
    });

    const mailOptions = {
      from: `"${fromName}" <${process.env.EMAIL_FROM}>`,
      to: recipients.join(','),
      subject,
      html: `<table style="width: 100%; font-family: Arial, sans-serif; background-color: #f9f9f9; padding: 20px;">
  <tr>
    <td align="center">
      <table style="max-width: 600px; width: 100%; background-color: #ffffff; border-radius: 8px; padding: 30px; box-shadow: 0 0 10px rgba(0,0,0,0.05);">
        <tr>
          <td align="center" style="padding-bottom: 20px;">
            <img src="https://cdn.dm.dynatrace.com/assets/Marketing/seo/dynatrace_web.png" alt="Dynatrace Logo" width="150" style="margin-bottom: 10px;" />
          </td>
        </tr>
        <tr>
          <td style="font-size: 16px; color: #333;">
            <p>Hi Team,</p>
            <p>Please find attached the latest <strong>Dynatrace Health Report</strong> generated by the AutomationEngine workflow.</p>
            <ul style="padding-left: 20px;">
              <li>Timeframe: <strong>Last 2 Hours</strong></li>
              <li>Included: Metrics, Problems, and Anomalies</li>
              <li>Format: Excel (.xlsx)</li>
            </ul>
            <p>Let us know if you need any clarifications or further insights.</p>
            <p style="margin-top: 30px;">Regards,<br /><strong>Observability Platform</strong></p>
          </td>
        </tr>
      </table>
    </td>
  </tr>
</table>`,
      attachments: [
        {
          filename: 'dynatrace-report.xlsx',
          path: filePath,
        },
      ],
    };

    await transporter.sendMail(mailOptions);
  } catch (error) {
    logger.error(`[${requestId}] ❌ Email send failed: ${error.stack || error}`);
    throw error;
  }
}
